server:
  port: 8666

spring:
  application:
    name: WELCOME-ORDER-SERVICE 
  boot:
    admin:
      client:
        url: http://localhost:1111/
        instance:
          prefer-ip: true # Forces Spring Boot Admin to target IP/Localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true # Forces Eureka registration via IP/Localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always