server:
  port: 8777

spring:
  application:
    name: BILL-SERVICE 
  boot:
    admin:
      client:
        url: http://localhost:1111/
        instance:
          prefer-ip: true # Forces Spring Boot Admin to register using IP/Localhost
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: booking-confirmation-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true # Forces Eureka to register using IP/Localhost instead of corporate machine name

# FIXED: Corrected indentation and removed duplicated keys
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0 
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

resilience4j:
  circuitbreaker:
    instances:
      failtra:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10 
        minimumNumberOfCalls: 5 
        failureRateThreshold: 50 
        waitDurationInOpenState: 10s 
        permittedNumberOfCallsInHalfOpenState: 3


  